<?php

return [
    "dashboard" => ["view"],
    "parties" => ["view", "create", "update", "delete", 'view-all-data'],
    "quotations" => ["view", "create", "update", "delete", 'view-all-data'],
    "purchases" => ["view", "create", "update", "delete", 'view-all-data'],
    "dueCollection" => ["view", "create", "update"],
    "ingredients" => ["view", "create", "update", "delete"],
    "units" => ["view", "create", "update", "delete"],
    "tables" => ["view", "create", "update", "delete"],
    "products" => ["view", "create", "update", "delete", 'view-all-data'],
    "categories" => ["view", "create", "update", "delete"],
    "menus" => ["view", "create", "update", "delete"],
    "modifierGroups" => ["view", "create", "update", "delete"],
    "itemModifiers" => ["view", "create", "update", "delete"],
    "moneyIn" => ["view"],
    "moneyOut" => ["view"],
    "transactions" => ["view"],
    "income" => ["view", "create", "update", "delete"],
    "incomeCategory" => ["view", "create", "update", "delete"],
    "expense" => ["view", "create", "update", "delete"],
    "expenseCategory" => ["view", "create", "update", "delete"],
    "coupon" => ["view", "create", "update", "delete"],
    "vat" => ["view", "create", "update", "delete"],
    "staff" => ["view", "create", "update", "delete"],
    "rolePermission" => ["view", "create", "update", "delete"],
    "generalSetting" => ["view", "update"],
    "notification" => ["view"],
    "subscription" => ["view", "create"],
    "sales" => ["view", "create", "update", "delete", 'view-all-data'],
    "printingOption" => ["view", "update"],
    "currency" => ["view", "update"],
    "paymentMethod" => ["view", "create", "update", "delete"],
    "salesReport" => ["view"],
    "subscriptionReport" => ["view"],
    "vatReport" => ["view"],
    "salesQuotationReport" => ["view"],
    "purchaseReport" => ["view"],
    "dueReport" => ["view"],
    "dueCollectionReport" => ["view", 'view-all-data'],
    "transactionReport" => ["view"],
    "incomeReport" => ["view"],
    "expenseReport" => ["view"],
    "settings" => ["view", "update"],
    "subscriptions" => ['view'],
    "download-apk" => ['view'],
];

