include: package:flutter_lints/flutter.yaml

formatter: 
  page_width: 120
  trailing_commas: preserve

analyzer:
  errors:
    no_leading_underscores_for_local_identifiers: ignore
    unused_result: ignore
